@echo off
echo Building WoW Backup Tool...
echo Installing pyinstaller if needed...
pip install pyinstaller
echo Running pyinstaller...
"C:\Users\%USERNAME%\AppData\Roaming\Python\Python313\Scripts\pyinstaller.exe" --onefile main.py
echo Build complete. Executable is in dist\main.exe
